-- MySQL Script generated by MySQL Workbench
-- Seg 29 Mai 2017 19:38:32 BRT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema es2tb2
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `es2tb2` ;

-- -----------------------------------------------------
-- Schema es2tb2
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `es2tb2` DEFAULT CHARACTER SET utf8 ;
USE `es2tb2` ;

-- -----------------------------------------------------
-- Table `es2tb2`.`Usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `es2tb2`.`Usuario` ;

CREATE TABLE IF NOT EXISTS `es2tb2`.`Usuario` (
  `idUsuario` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  `dataNascimento` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idUsuario`),
  UNIQUE INDEX `nome_UNIQUE` (`nome` ASC))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
